Set ConfigSpace requirement < 1: >=0.7,<1 With ConfigSpace 1.*, we got an erorr because parameter `q` is not used anymore in UniformFloatHyperparameter:
   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  src/orion/testing/algo.py:301: in create_algo
      algo = create_algo(space=original_space, algo_type=cls.algo_type, **algo_kwargs)
  src/orion/core/worker/primary_algo.py:106: in create_algo
      algorithm = algo_type(spaces.pop(), *algo_args, **algo_kwargs)
  src/orion/algo/dehb/dehb.py:320: in __init__
      configspace = convert_space(self.space)
  .tox/py-all/lib/python3.8/site-packages/sspace/convert.py:59: in convert_space
      hp = fun(v)
  .tox/py-all/lib/python3.8/site-packages/sspace/convert.py:121: in _convert_real
      return _prior_dispatch.get(self.prior_name, _not_implemented(self.prior_name))()
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

      def make_uniform():
  >       return csh.UniformFloatHyperparameter(
              self.name,
              lower=a,
              upper=b,
              default_value=self.default_value,
              q=None,
              log=False,
          )
  E       TypeError: __init__() got an unexpected keyword argument 'q'